<a href="https://colab.research.google.com/github/abhinavbammidi1401/ML_Assignment2/blob/main/ML_Test_30_8_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

Data Loading and Inspection

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/2015.csv')
#loading the dataset into a pandas dataframe

In [ ]:
df

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
154,Benin,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
155,Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
156,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
157,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [ ]:
df.dtypes

Country                           object
Region                            object
Happiness Rank                     int64
Happiness Score                  float64
Standard Error                   float64
Economy (GDP per Capita)         float64
Family                           float64
Health (Life Expectancy)         float64
Freedom                          float64
Trust (Government Corruption)    float64
Generosity                       float64
Dystopia Residual                float64
dtype: object

In [ ]:
df.describe()
#this gives us a clear view on how many rows are there and what are various measures of the dataset like min. value, max value, etc.

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,79.493671,5.375734,0.047885,0.846137,0.991046,0.630259,0.428615,0.143422,0.237296,2.098977
std,45.754363,1.145010,0.017146,0.403121,0.272369,0.247078,0.150693,0.120034,0.126685,0.553550
min,1.000000,2.839000,0.018480,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.328580
25%,40.250000,4.526000,0.037268,0.545808,0.856823,0.439185,0.328330,0.061675,0.150553,1.759410
50%,79.500000,5.232500,0.043940,0.910245,1.029510,0.696705,0.435515,0.107220,0.216130,2.095415
75%,118.750000,6.243750,0.052300,1.158448,1.214405,0.811013,0.549092,0.180255,0.309883,2.462415
max,158.000000,7.587000,0.136930,1.690420,1.402230,1.025250,0.669730,0.551910,0.795880,3.602140

In [ ]:
df.drop('Trust (Government Corruption)', axis=1, inplace=True)

In [ ]:
df

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Health (Life Expectancy)
0,Switzerland,Western Europe,1,7.587,1.39651,0.94143
1,Iceland,Western Europe,2,7.561,1.30232,0.94784
2,Denmark,Western Europe,3,7.527,1.32548,0.87464
3,Norway,Western Europe,4,7.522,1.45900,0.88521
4,Canada,North America,5,7.427,1.32629,0.90563
...,...,...,...,...,...,...
153,Rwanda,Sub-Saharan Africa,154,3.465,0.22208,0.42864
154,Benin,Sub-Saharan Africa,155,3.340,0.28665,0.31910
155,Syria,Middle East and Northern Africa,156,3.006,0.66320,0.72193
156,Burundi,Sub-Saharan Africa,157,2.905,0.01530,0.22396
157,Togo,Sub-Saharan Africa,158,2.839,0.20868,0.28443

Missing Values

In [ ]:
df.isnull().sum()
#as we can see from the results, below there appear to be no missing values in this dataset.

Country                     0
Region                      0
Happiness Rank              0
Happiness Score             0
Economy (GDP per Capita)    0
Health (Life Expectancy)    0
dtype: int64

Binning

In [ ]:
# Define bin groups
happiness_bins = ['Low_happiness','Medium_happiness','High_happiness']
happiness_labels = ["1-3","4-6","7-9"]

#bin groups
#1-3
#4-6
#7-9

One-Hot Encoding

In [ ]:
pd.unique(df['Region'])
#identifying how many unique values are there in the region column

array(['Western Europe', 'North America', 'Australia and New Zealand',
       'Middle East and Northern Africa', 'Latin America and Caribbean',
       'Southeastern Asia', 'Central and Eastern Europe', 'Eastern Asia',
       'Sub-Saharan Africa', 'Southern Asia'], dtype=object)

In [ ]:
#df_encoded = pd.get_dummies(df, columns=['Region'], drop_first=True)

#dummy encoding is producing too many unusable columns,
#so we can only use one hot encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder
df = encoder(df['Region'])

TypeError: ignored